component_management:
  individual_components:
    - component_id: "XO.EntityFrameworkCore.NpgsqlJsonSerializerOptions"
      paths:
        - "XO.EntityFrameworkCore.NpgsqlJsonSerializerOptions/"

comment:
  layout: "header, diff, flags, components"  # show component info in the PR comment
